name: Build Revenge

on:
   workflow_dispatch:
    inputs:
        ipa_url:
            description: "Direct link to the decrypted IPA"
            default: ""
            required: true
            type: string

jobs:
  build-tweak:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
    
      - name: Xcode Select Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.1.0'

      - name: Check cache
        run: |
          echo upstream_heads=`git ls-remote https://github.com/theos/theos | head -n 1 | cut -f 1`-`git ls-remote https://github.com/theos/sdks | head -n 1 | cut -f 1` >> $GITHUB_ENV

      - name: Use cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ runner.os }}-${{ env.upstream_heads }}

      - name: Install Theos
        run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"

      - name: Build packages
        run: |
          export PATH="$(brew --prefix make)/libexec/gnubin:$PATH"
          export THEOS="${{ github.workspace }}/theos"
          rm -rf packages && make clean && make package FINALPACKAGE=1 && make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: "package"
          path: ${{ github.workspace }}/packages/*-arm.deb

      - name: Upload rootless package
        uses: actions/upload-artifact@v4
        with:
          name: "rootless package"
          path: ${{ github.workspace }}/packages/*-arm64.deb

  build-ipa:
    runs-on: macos-14
    needs: build-tweak

    steps:
      - name: Xcode Select Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.1.0'

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Download and Unzip Orion
        run: |
          curl -L -o Orion.zip https://github.com/theos/orion/releases/download/1.0.1/Orion_1.0.1.zip
          unzip Orion.zip -d Orion

      - name: Download Discord IPA
        run: |
          curl -L -o discord.ipa ${{ github.event.inputs.ipa_url }}

      - name: Clone Azule and inject tweak
        run: |
          git clone https://github.com/Al4ise/Azule.git
          ./Azule/azule -i discord.ipa -o Revenge -f dev.theos.orion14_1.0.1_iphoneos-arm.deb mod.revenge.app_0.0.2_iphoneos-arm.deb

      - name: Upload Revenge.ipa as artifact
        uses: actions/upload-artifact@v4
        with:
            name: ipa
            path: ./Revenge.ipa
     